project_identifier: "iomp"
base_url: "https://api.crowdin.com"
api_token: "${env:CROWDIN_API_TOKEN}"

files:
  - source: "client/src/locales/en/translation.json"
    translation: "client/src/locales/%two_letters_code%/translation.json"
    # %two_letters_code% will be 'hi', 'te', etc. for target languages
